import { Element } from "./types";

export const ELEMENTS: Element[] = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    electronConfiguration: "1s¹",
    commonIons: [{ formula: "H⁺", charge: 1, name: "Proton" }],
    electronegativity: 2.2,
    period: 1,
    group: 1,
    color: "#00bfff",
    description: "The lightest and most abundant element in the universe.",
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.003,
    category: "noble-gas",
    electronConfiguration: "1s²",
    commonIons: [],
    electronegativity: null,
    period: 1,
    group: 18,
    color: "#ff69b4",
    description: "Noble gas; used in balloons and cryogenics.",
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.941,
    category: "alkali-metal",
    electronConfiguration: "[He] 2s¹",
    commonIons: [{ formula: "Li⁺", charge: 1, name: "Lithium ion" }],
    electronegativity: 0.98,
    period: 2,
    group: 1,
    color: "#ff4444",
    description: "Lightest metal; used in batteries and mood stabilizers.",
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    electronConfiguration: "[He] 2s² 2p²",
    commonIons: [{ formula: "C⁴⁺", charge: 4, name: "Carbocation" }],
    electronegativity: 2.55,
    period: 2,
    group: 14,
    color: "#888888",
    description: "Basis of all organic chemistry; exists as diamond and graphite.",
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    electronConfiguration: "[He] 2s² 2p³",
    commonIons: [
      { formula: "NO₃⁻", charge: -1, name: "Nitrate" },
      { formula: "NH₄⁺", charge: 1, name: "Ammonium" },
    ],
    electronegativity: 3.04,
    period: 2,
    group: 15,
    color: "#6699ff",
    description: "Makes up 78% of Earth's atmosphere.",
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    electronConfiguration: "[He] 2s² 2p⁴",
    commonIons: [
      { formula: "O²⁻", charge: -2, name: "Oxide" },
      { formula: "OH⁻", charge: -1, name: "Hydroxide" },
    ],
    electronegativity: 3.44,
    period: 2,
    group: 16,
    color: "#ff4411",
    description: "Essential for respiration and combustion.",
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    electronConfiguration: "[He] 2s² 2p⁵",
    commonIons: [{ formula: "F⁻", charge: -1, name: "Fluoride" }],
    electronegativity: 3.98,
    period: 2,
    group: 17,
    color: "#00ff88",
    description: "Most electronegative element; highly reactive halogen.",
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.18,
    category: "noble-gas",
    electronConfiguration: "[He] 2s² 2p⁶",
    commonIons: [],
    electronegativity: null,
    period: 2,
    group: 18,
    color: "#ff9900",
    description: "Used in neon signs; emits distinctive orange-red glow.",
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.99,
    category: "alkali-metal",
    electronConfiguration: "[Ne] 3s¹",
    commonIons: [{ formula: "Na⁺", charge: 1, name: "Sodium ion" }],
    electronegativity: 0.93,
    period: 3,
    group: 1,
    color: "#ff4444",
    description: "Essential for nerve function; component of table salt.",
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth-metal",
    electronConfiguration: "[Ne] 3s²",
    commonIons: [{ formula: "Mg²⁺", charge: 2, name: "Magnesium ion" }],
    electronegativity: 1.31,
    period: 3,
    group: 2,
    color: "#ffaa00",
    description: "Essential for chlorophyll; burns with intense white flame.",
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition-metal",
    electronConfiguration: "[Ne] 3s² 3p¹",
    commonIons: [{ formula: "Al³⁺", charge: 3, name: "Aluminum ion" }],
    electronegativity: 1.61,
    period: 3,
    group: 13,
    color: "#aaaaaa",
    description: "Most abundant metal in Earth's crust.",
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.086,
    category: "metalloid",
    electronConfiguration: "[Ne] 3s² 3p²",
    commonIons: [{ formula: "Si⁴⁺", charge: 4, name: "Silicon ion" }],
    electronegativity: 1.9,
    period: 3,
    group: 14,
    color: "#6688aa",
    description: "Basis of semiconductor technology and computer chips.",
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    commonIons: [
      { formula: "Cl⁻", charge: -1, name: "Chloride" },
      { formula: "ClO⁻", charge: -1, name: "Hypochlorite" },
    ],
    electronegativity: 3.16,
    period: 3,
    group: 17,
    color: "#aaff00",
    description: "Used in water purification; component of table salt.",
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble-gas",
    electronConfiguration: "[Ne] 3s² 3p⁶",
    commonIons: [],
    electronegativity: null,
    period: 3,
    group: 18,
    color: "#ff69b4",
    description: "Third most abundant gas in Earth's atmosphere.",
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    electronConfiguration: "[Ar] 4s¹",
    commonIons: [{ formula: "K⁺", charge: 1, name: "Potassium ion" }],
    electronegativity: 0.82,
    period: 4,
    group: 1,
    color: "#ff4444",
    description: "Essential for plant growth and nerve signaling.",
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth-metal",
    electronConfiguration: "[Ar] 4s²",
    commonIons: [
      { formula: "Ca²⁺", charge: 2, name: "Calcium ion" },
      { formula: "CaCO₃", charge: 0, name: "Calcium carbonate" },
    ],
    electronegativity: 1.0,
    period: 4,
    group: 2,
    color: "#ffaa00",
    description: "Essential for bones and teeth; most abundant mineral in body.",
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition-metal",
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    commonIons: [
      { formula: "Fe²⁺", charge: 2, name: "Iron(II) / Ferrous" },
      { formula: "Fe³⁺", charge: 3, name: "Iron(III) / Ferric" },
    ],
    electronegativity: 1.83,
    period: 4,
    group: 8,
    color: "#cc6633",
    description: "Most used metal; core of Earth; essential in hemoglobin.",
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition-metal",
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    commonIons: [
      { formula: "Cu⁺", charge: 1, name: "Copper(I) / Cuprous" },
      { formula: "Cu²⁺", charge: 2, name: "Copper(II) / Cupric" },
    ],
    electronegativity: 1.9,
    period: 4,
    group: 11,
    color: "#ff8844",
    description: "Excellent conductor of electricity; used in wiring.",
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition-metal",
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    commonIons: [{ formula: "Zn²⁺", charge: 2, name: "Zinc ion" }],
    electronegativity: 1.65,
    period: 4,
    group: 12,
    color: "#99aaaa",
    description: "Essential trace element; used in galvanization.",
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.868,
    category: "transition-metal",
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    commonIons: [{ formula: "Ag⁺", charge: 1, name: "Silver ion" }],
    electronegativity: 1.93,
    period: 5,
    group: 11,
    color: "#dddddd",
    description: "Best electrical conductor; antimicrobial properties.",
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.967,
    category: "transition-metal",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    commonIons: [
      { formula: "Au⁺", charge: 1, name: "Gold(I) / Aurous" },
      { formula: "Au³⁺", charge: 3, name: "Gold(III) / Auric" },
    ],
    electronegativity: 2.54,
    period: 6,
    group: 11,
    color: "#ffd700",
    description: "Highly valued precious metal; excellent conductor.",
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition-metal",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    commonIons: [
      { formula: "Pb²⁺", charge: 2, name: "Lead(II) / Plumbous" },
      { formula: "Pb⁴⁺", charge: 4, name: "Lead(IV) / Plumbic" },
    ],
    electronegativity: 2.33,
    period: 6,
    group: 14,
    color: "#778899",
    description: "Dense heavy metal; toxic; used in radiation shielding.",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  "alkali-metal": "Alkali Metal",
  "alkaline-earth-metal": "Alkaline Earth Metal",
  "transition-metal": "Transition Metal",
  "post-transition-metal": "Post-Transition Metal",
  metalloid: "Metalloid",
  nonmetal: "Nonmetal",
  halogen: "Halogen",
  "noble-gas": "Noble Gas",
  lanthanide: "Lanthanide",
  actinide: "Actinide",
};

export const CATEGORY_COLORS: Record<string, string> = {
  "alkali-metal": "from-red-600 to-red-900",
  "alkaline-earth-metal": "from-orange-500 to-orange-800",
  "transition-metal": "from-yellow-500 to-yellow-800",
  "post-transition-metal": "from-gray-400 to-gray-700",
  metalloid: "from-teal-500 to-teal-800",
  nonmetal: "from-blue-500 to-blue-800",
  halogen: "from-green-400 to-green-700",
  "noble-gas": "from-purple-400 to-purple-700",
  lanthanide: "from-pink-400 to-pink-700",
  actinide: "from-fuchsia-400 to-fuchsia-700",
};
